---
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: 96221dc741cb30cc0136999083dc6bd0e2113000
    hooks:
      - id: go-fmt
      - id: go-lint
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.47.2
    hooks:
      - id: golangci-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: forbid-binary
      - id: markdownlint
      - id: shfmt
