---
name: Tests via pre-commit
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Nix
        uses: cachix/install-nix-action@v17
      - name: Run pre-commit
        run: nix develop -c -- pre-commit run -a
